### ISSUE TITLE
Make Route.RouteStop conform to Protocol Hashable

### ISSUE THREAD

**Issue by PhilippMatthes** [kiliankoe/DVB#30]
I used the following code in an extension, which worked:

```
public var hashValue: Int {
        return self.name.hashValue
}
    
public static func ==(lhs: Route.RouteStop, rhs: Route.RouteStop) -> Bool {
        return lhs.name == rhs.name
}
```

Unfortunately, I will not send a pull request from my forked repo as it contains some further changes specifically for my App.

**Comment by kiliankoe** [comment]
Thanks! 😊

We'll probably get around custom implementations of this thanks to Swift 4.1 being close to release. But it definitely makes sense to conform most types to Equatable and Hashable.

I'm also very interested in usages of this if you're willing to share! You can also hit me up via mail if you'd prefer.

**Comment by kiliankoe** [comment]
I'm currently in the process of cleaning a few things up, fixing leftover TODOs and FIXMEs and hopefully getting a new release of this done at some point 🙈 Most types now conform to Equatable thanks to Swift 4.1 and I added a few Hashable conformances where Swift could automatically generate those as well. And and extra one for `Route.RouteStop` :P
